# Generated by Django 5.1 on 2024-08-25 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название сайта')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон номер')),
                ('link_whatsapp', models.URLField(verbose_name='Ватсап номер')),
                ('link_telegram', models.URLField(verbose_name='Телеграм номер')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Настройка',
                'verbose_name_plural': 'Настройки',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=255, verbose_name='Название раздел')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.setting', verbose_name='Настрока')),
            ],
        ),
    ]
