# Generated by Django 5.1 on 2024-08-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_serviceprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprice',
            name='price',
            field=models.CharField(max_length=255, verbose_name='цена за кг'),
        ),
    ]
