# Generated by Django 5.1 on 2024-08-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_setting_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='image',
            field=models.ImageField(null=True, upload_to='section/', verbose_name='фото'),
        ),
        migrations.AddField(
            model_name='setting',
            name='location',
            field=models.CharField(default=1, max_length=2000, verbose_name='локация'),
            preserve_default=False,
        ),
    ]
